15:58:58.371  🔍 DIAGNOSTIC: Script has started running successfully!  -  Server - Script:4
15:58:58.371  ⚡ SYSTEM: R6 Dynamic Animation Swapper Active!  -  Server - Script:4
15:58:58.624  🔍 DIAGNOSTIC: Player joined: Pancake_aks  -  Server - Script:7
15:58:58.731  🔍 DIAGNOSTIC: Character spawned for: Pancake_aks  -  Server - Script:10
	15:58:58.731  ⏳ Waiting for Animate script...  -  Server - Script:12
		15:58:58.732  ⏳ Waiting for run and walk folders...  -  Server - Script:19
			15:58:58.732  ⏳ Waiting for Animation tracks...  -  Server - Script:28
				15:59:03.748  Infinite yield possible on 'Workspace.Pancake_aks.Animate.walk:WaitForChild("Animation")'  -  Studio
				15:59:03.748  Stack Begin  -  Studio
				15:59:03.748  Script 'Workspace.SpawnLocation.Script', Line 12  -  Studio - Script:12
				15:59:03.748  Stack End  -  Studio
				15:59:06.825  DataStoreService: StudioAccessToApisNotAllowed: Studio access to APIs is not allowed. API: GetAsync, Data Store: HackaTime_PlayTest_Data  -  Studio
				15:59:08.802  ❌ ERROR: Could not find the internal 'Animation' object. Are you sure the game is set to R6?  -  Server - Script:33